# Generated by Django 2.0 on 2017-12-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduling',
            old_name='data',
            new_name='date',
        ),
    ]
