# Generated by Django 2.0 on 2017-12-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171212_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='end_time',
            field=models.TimeField(verbose_name='fim'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='start_time',
            field=models.TimeField(verbose_name='inicio'),
        ),
    ]
